// Generated by Biliverse.github.io/scripts/build-settings.mjs. Do not edit.
const MODULE = "Global";
const fields = [{"key":"ForceHost","name":"强制CDN主机名类型","type":"number","defaultValue":1,"description":"请设置强制返回的CDN主机名类型。","options":[{"key":0,"label":"IP: 返回远端DNS解析地址（强烈不推荐！严重影响域名分流规则与CDN重定向）"},{"key":1,"label":"HTTP: 返回HTTP域名（推荐，免去重定向时MitM操作）"},{"key":2,"label":"HTTPS: 返回HTTPS域名（不推荐，重定向时需对指定域名启用MitM）"}]},{"key":"Locales","name":"启用自动识别与分流功能的地区","type":"array","defaultValue":["CHN","HKG","TWN"],"description":"请选择启用自动识别与分流功能的地区。","options":[{"key":"CHN","label":"🇨🇳中国大陆"},{"key":"HKG","label":"🇭🇰中国香港"},{"key":"MAC","label":"🇲🇴中国澳门"},{"key":"TWN","label":"🇹🇼中国台湾"}]},{"key":"Proxies.CHN","name":"[🇨🇳中国大陆] 代理策略名称","type":"string","defaultValue":"DIRECT","description":"请填写此地区的代理或策略组名称。"},{"key":"Proxies.HKG","name":"[🇭🇰中国香港] 代理策略名称","type":"string","defaultValue":"🇭🇰香港","description":"请填写此地区的代理或策略组名称。"},{"key":"Proxies.MAC","name":"[🇲🇴中国澳门] 代理策略名称","type":"string","defaultValue":"🇲🇴澳门","description":"请填写此地区的代理或策略组名称。"},{"key":"Proxies.TWN","name":"[🇹🇼中国台湾] 代理策略名称","type":"string","defaultValue":"🇹🇼台湾","description":"请填写此地区的代理或策略组名称。"},{"key":"Storage","name":"[储存] 配置类型","type":"string","defaultValue":"Argument","description":"选择要使用的配置类型。未设置此选项或不通过此选项的旧版本的配置顺序依旧是 PersistentStore (BoxJs) > $argument > database。","options":[{"key":"Argument","label":"优先使用来自 $argument 的配置，$argument 不包含的设置项由 PersistentStore (BoxJs) 提供"},{"key":"PersistentStore","label":"只使用 PersistentStore (BoxJs) 提供的配置"},{"key":"database","label":"只使用由作者的 database.mjs 文件提供的默认配置，其他任何自定义配置不再起作用"}]},{"key":"LogLevel","name":"[调试] 日志等级","type":"string","defaultValue":"WARN","description":"选择脚本日志的输出等级，低于所选等级的日志将全部输出。","options":[{"key":"OFF","label":"关闭"},{"key":"ERROR","label":"❌ 错误"},{"key":"WARN","label":"⚠️ 警告"},{"key":"INFO","label":"ℹ️ 信息"},{"key":"DEBUG","label":"🅱️ 调试"},{"key":"ALL","label":"全部"}]}];

import { $app, Storage, Lodash as _ } from "@nsnanocat/util";

// MODULE and fields are injected by scripts/build-settings.mjs.
export function settingsResponse(request, settings) {
	const url = new URL(request.url);
	if (url.origin !== "https://biliverse.github.io" || url.pathname !== `/settings/api/${MODULE}`) return;
	const moduleName = MODULE;
	const moduleFields = fields;
	const storedSettings = Storage.getItem("BiliBili", {})?.[moduleName]?.Settings ?? {};
	const moduleSettings = storedSettings.Storage === "PersistentStore" ? storedSettings : (moduleName === MODULE ? settings : {});
	const headers = { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" };
	const reply = (status, data) => ({ status, headers, body: JSON.stringify(data) });
	if ($app === "Worker") return reply(501, { error: "设置页面仅支持本地插件脚本，不支持云端 Rewrite 模式。" });
	const requestHeaders = Object.fromEntries(Object.entries(request.headers ?? {}).map(([key, value]) => [key.toLowerCase(), value]));
	if (requestHeaders["x-biliverse-settings"] !== "1" || (requestHeaders.origin && requestHeaders.origin !== url.origin)) return reply(403, { error: "请从 Biliverse 设置页面访问。" });
	if (request.method === "HEAD") return { status: 200, headers, body: "" };
	if (request.method === "GET") {
		const values = Object.fromEntries(moduleFields.map(field => [field.key, _.get(moduleSettings, field.key, field.defaultValue)]));
		values.Storage = Storage.getItem("BiliBili", {})?.[moduleName]?.Settings?.Storage ?? globalThis.$argument.Storage ?? "Argument";
		return reply(200, { module: moduleName, fields: moduleFields, values });
	}
	if (request.method !== "POST") return reply(405, { error: "仅支持 GET、POST" });
	if (!requestHeaders["content-type"]?.startsWith("application/json")) return reply(415, { error: "请使用 JSON 请求体。" });
	if (typeof request.body !== "string" || request.body.length > 65536) return reply(400, { error: "请求体为空或过大。" });
	let input;
	try { input = JSON.parse(request.body); } catch { return reply(400, { error: "JSON 格式错误。" }); }
	if (!input?.values || typeof input.values !== "object" || Array.isArray(input.values)) return reply(400, { error: "缺少设置值。" });
	const entries = Object.entries(input.values);
	if (!entries.length) return reply(400, { error: "没有需要保存的设置。" });
	for (const [key, value] of entries) {
		const field = moduleFields.find(item => item.key === key);
		if (!field) return reply(400, { error: `未知设置：${key}` });
		const values = field.type === "array" ? value : [value];
		const validType = field.type === "array" ? Array.isArray(value) : typeof value === field.type;
		if (!validType || (field.type === "number" && !Number.isFinite(value)) || (typeof value === "string" && value.length > 2048)) return reply(400, { error: `设置类型错误：${key}` });
		if (field.options && values.some(item => !field.options.some(option => option.key === item))) return reply(400, { error: `选项不存在：${key}` });
		if (field.type === "array" && new Set(value).size !== value.length) return reply(400, { error: `选项重复：${key}` });
	}
	// Preserve effective arguments and unexposed settings when switching to local storage.
	const stored = Storage.getItem("BiliBili", {});
	const savedRoot = _.merge({}, stored, { [moduleName]: { Settings: _.merge({}, moduleSettings, stored?.[moduleName]?.Settings) } });
	const saved = savedRoot[moduleName].Settings;
	for (const [key, value] of entries) _.set(saved, key, value);
	savedRoot[moduleName].Settings = saved;
	if (!Storage.setItem("BiliBili", savedRoot)) return reply(500, { error: "本地存储写入失败，设置未保存。" });
	return reply(200, { saved: true });
}
